### ISSUE TITLE
Time input not parsed unless it contains colon

### ISSUE THREAD

**Issue by BlockWorld** [Hugernot/TimeJuggler9400#1]
`parseTime("190 minutes");` yields `"Colon missing"` when "190 minutes" is an input given in the example

**Comment by BlockWorld** [comment]
Oddly, you can input "0:190 minutes" when 190 is over 60. It works, and yields the expected output of 190 minutes.

**Comment by Hugernot** [comment]
Lmao, yeah the colon acts as a separator between the hours and the minutes, and because parseTime() turns a given time into a manageable number (minutes), I felt that it wasn't necessary to make it handle minutes being put in, because it just spits out the input basically. If you just wanted to add minutes do `parseTime("6:00") + 20` it'll have the same result as `parseTime("6:00") + parseTime("0:20")`.

**Comment by BlockWorld** [comment]
ok lol
